### ISSUE TITLE
Error: Cannot find module '../build/Release/sharp.node'

### ISSUE THREAD

**Issue by chawax** [GatsbyCentral/gatsby-starter-wordpress#34] opened 2018-11-17 20:10 UTC
Hi,

I am discovering Gatsby and try this starter. I changed the `baseUrl` parameter in `gatsby-config.js` file. But when I run `gatsby develop` I have the following errors : 

```
success open and validate gatsby-config — 0.009 s
success load plugins — 0.268 s
error Plugin gatsby-transformer-sharp returned an error


  Error: Cannot find module '../build/Release/sharp.node'
```

When I run `npm install` I have other errors : 

```
> deasync@0.1.13 install /Users/olivierthierry/Sites/gatsby-terresceltes/node_modules/deasync
> node ./build.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/olivierthierry/Sites/gatsby-terresceltes/node_modules/deasync
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed
```

Am I missing something ?

**Comment by chmac** [comment] 2018-11-20 12:00
@chawax I'd guess that you're on macOS and need to install the xcode command line tools package. It looks like one of the dependencies cannot build because of that. Do you have the xcode command line tools installed?

**Comment by chmac** [comment] 2018-11-20 20:39
Strange, no idea why that would relate to your node version. Glad you got it fixed. Will close the issue now assuming the issue is resolved.

**Closed by chmac** 2018-11-20 20:39 UTC
Labels: waiting for reply
