### ISSUE TITLE
`Cannot query allWordpressWpUsers...` and `"author" must not have a selection` errors on initial build

### ISSUE THREAD

**Issue by iandunn** [GatsbyCentral/gatsby-starter-wordpress#49] opened 2019-11-22 08:37 UTC
Hi, I'm testing this out, and am getting a couple errors during the initial `gatsby develop`:

* `gatsby new test https://github.com/GatsbyCentral/gatsby-starter-wordpress`
* updated `gatsby-config.js` to set `baseUrl       : 'iandunn.name',`
* `gatsby develop`

Specifically:

> Cannot query field "allWordpressWpUsers"

...and

> Field "author" must not have a selection since type "Int" has no subfield

```
success Downloading remote files — 19/19 - 0.502 s
success source and transform nodes - 18.965 s
success Add explicit types - 0.018 s
warn Multiple node fields resolve to the same GraphQL field `wordpress__wp_media.guid` - [`guid___NODE`,
`guid`]. Gatsby will use `guid___NODE`.
success Add inferred types - 0.222 s
success Processing types - 0.142 s
warn There are conflicting field types in your data.

If you have explicitly defined a type for those fields, you can safely ignore this warning message.
Otherwise, Gatsby will omit those fields from the GraphQL schema.

If you know all field types in advance, the best strategy is to explicitly define them with the `createTypes`
action, and skip inference with the `@dontInfer` directive.
See https://www.gatsbyjs.org/docs/actions/#createTypes
wordpress__wp_media.media_details.width:
 - type: number
   value: 1696
 - type: string
   value: '403'
wordpress__wp_media.media_details.height:
 - type: date
   value: '1024'
 - type: number
   value: 722
 - type: string
   value: '403'
wordpress__wp_media.media_details.image_meta.aperture:
 - type: number
   value: 2.4
 - type: string
   value: '0'
wordpress__wp_media.media_details.image_meta.created_timestamp:
 - type: number
   value: 1039348800
 - type: string
   value: '0'
wordpress__wp_media.media_details.image_meta.focal_length:
 - type: number
   value: 0
 - type: string
   value: '0'
wordpress__wp_media.media_details.image_meta.iso:
 - type: number
   value: 0
 - type: string
   value: '0'
wordpress__wp_media.media_details.image_meta.shutter_speed:
 - type: number
   value: 0
 - type: string
   value: '0'
success building schema - 0.470 s
Cannot query field "allWordpressWpUsers" on type "Query". Did you mean "allWordpressWpSearch", "allWordpressWpTypes", "allWordpressWpStatuses", "allWordpressPage", or "allWordpressWpMedia"?

GraphQL request:3:11
2 |         {
3 |           allWordpressWpUsers {
  |           ^
4 |             edges {

 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

Cannot query field "allWordpressWpUsers" on type "Query". Did you mean "allWordpressWpSearch", "allWordpressWpTypes", "allWordpressWpStatuses", "allWordpressPage", or "allWordpressWpMedia"?

GraphQL request:3:11
2 |         {
3 |           allWordpressWpUsers {
  |           ^
4 |             edges {

success createPages - 0.555 s
success createPagesStatefully - 0.050 s
success onPreExtractQueries - 0.018 s
success update schema - 0.054 s

 ERROR #85909  GRAPHQL

Field "author" must not have a selection since type "Int" has no subfields
```

In the browser, it get this error:

```
GraphQL Error Field "author" must not have a selection since type "Int" has no subfields.

  file: /Users/iandunn/vhosts/localhost/gatsby/src/templates/post.js
```

I tried it with random site's `baseUrl`, though, and it worked fine. 

If I switch back to my `baseUrl`, and then remove all the references to `author` and `wordpressWpUsers`, then it works.

**Comment by hello-world-its-rich** [comment] 2019-12-19 22:37
Hi @iandunn, happy to help with this. How does the rest of gatsby-config.js look for you?  

Be sure the other options under are accurate.  

Here is mine for example 

`plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sass',
    {
      resolve: 'gatsby-source-wordpress',
      options: {
        // The base url to your WP site.
        baseUrl: 'dev-richgatsbyjs.pantheonsite.io',
        // WP.com sites set to true, WP.org set to false
        hostingWPCOM: false,
        // The protocol. This can be http or https.
        protocol: 'https',
        // Use 'Advanced Custom Fields' Wordpress plugin
        useACF: false,
        auth: {},
        // Set to true to debug endpoints on 'gatsby build'
        verboseOutput: false,
      },
    },`

See my full site here, just built, work in progress: https://projects.richandrews.me/

**Comment by louisrli** [comment] 2020-06-26 10:16
I'm seeing this too with a very basic wordpress.com setup, all I changed was the baseurl + hostingWPCOM to true.

**Comment by chmac** [comment] 2020-07-01 10:23
This is a tough issue. The produced GraphQL schema depends on what your WordPress config looks like. If you have a single post with a featured image, then the post schema gets a featured image field, if not, then it doesn't. Bottom line, you need to carefully setup WordPress to match our demo site's config. We've done our best to document that in the README. Very open to PRs which improve the readme, or add specific tests / better errors to make this stuff clearer.

In the meantime, I'll close this issue as it's not an error that we can address in the starter, it's an issue caused by the WordPress site's configuration.

**Closed by chmac** 2020-07-01 10:23 UTC
