### ISSUE TITLE
There was an error in your GraphQL query

### ISSUE THREAD

**Issue by kosvrouvas** [GatsbyCentral/gatsby-starter-wordpress#55] opened 2020-04-22 14:23 UTC
This happened to every website I try to run locally simultaneously:

```
There was an error in your GraphQL query:
The fragment "PostListFields" does not exist.

here was an error in your GraphQL query:

Field "author" must not have a selection since type "Int" has no subfields.

This can happen if you e.g. accidentally added { } to the field "author". If you didn't expect "author" to be of type "Int" make sure that your input source and/or plugin is correct.

File: src/components/PostList.js:76:12


 ERROR #85922  GRAPHQL

There was an error in your GraphQL query:

Field "author" must not have a selection since type "Int" has no subfields.

This can happen if you e.g. accidentally added { } to the field "author". If you didn't expect "author" to be of type "Int" make sure that your input source and/or plugin is correct.

File: src/templates/post.js:153:14


 ERROR #85908  GRAPHQL

There was an error in your GraphQL query:

The fragment "PostListFields" does not exist.

  38 | export const pageQuery = graphql`
  39 |   query AuthorPage($id: String!) {
  40 |     site {
  41 |       siteMetadata {
  42 |         title
  43 |       }
  44 |     }
  45 |     wordpressWpUsers(id: { eq: $id }) {
  46 |       name
  47 |       authored_wordpress__POST {
> 48 |         ...PostListFields
     |         ^^^^^^^^^^^^^^^^^
  49 |       }
  50 |     }
  51 |   }
  52 | `
  53 |

File: src/templates/author.js


 ERROR #85908  GRAPHQL

There was an error in your GraphQL query:

The fragment "PostListFields" does not exist.

  33 |
  34 | export const pageQuery = graphql`
  35 |   query IndexQuery($limit: Int!, $skip: Int!) {
  36 |     allWordpressPost(
  37 |       sort: { fields: date, order: DESC }
  38 |       limit: $limit
  39 |       skip: $skip
  40 |     ) {
  41 |       edges {
  42 |         node {
> 43 |           ...PostListFields
     |           ^^^^^^^^^^^^^^^^^
  44 |         }
  45 |       }
  46 |     }
  47 |   }
  48 | `
  49 |

File: src/templates/blog.js


 ERROR #85908  GRAPHQL

There was an error in your GraphQL query:

The fragment "PostListFields" does not exist.

  35 |       siteMetadata {
  36 |         title
  37 |       }
  38 |     }
  39 |     allWordpressPost(
  40 |       filter: { categories: { elemMatch: { slug: { eq: $slug } } } }
  41 |     ) {
  42 |       totalCount
  43 |       edges {
  44 |         node {
> 45 |           ...PostListFields
     |           ^^^^^^^^^^^^^^^^^
  46 |         }
  47 |       }
  48 |     }
  49 |   }
  50 | `
  51 |

File: src/templates/category.js


 ERROR #85908  GRAPHQL

There was an error in your GraphQL query:

The fragment "PostListFields" does not exist.

  33 |   query TagPage($slug: String!) {
  34 |     site {
  35 |       siteMetadata {
  36 |         title
  37 |       }
  38 |     }
  39 |     allWordpressPost(filter: { tags: { elemMatch: { slug: { eq: $slug } } } }) {
  40 |       totalCount
  41 |       edges {
  42 |         node {
> 43 |           ...PostListFields
     |           ^^^^^^^^^^^^^^^^^
  44 |         }
  45 |       }
  46 |     }
  47 |   }
  48 | `
  49 |

File: src/templates/tag.js

failed extract queries from components - 0.956s

File: src/templates/author.js
```

**Comment by chmac** [comment] 2020-04-28 11:26
@kosvrouvas Have you upgraded some packages? Gatsby is quite aggressive at pushing out updates, and in the past some of their updates broke the starter. They made changes to the GraphQL schema produced by the WordPress plugin which caused the issue. It might be the same again.

**Comment by chmac** [comment] 2020-04-28 11:29
@kosvrouvas I've just checked and the starter works for me using `yarn` to install dependencies and `yarn start` to run it. I assume the issue must be caused by an update, etc. I'm not actively using this starer these days, so not sure if it still works with the most recent version of Gatsby. If you find and are able to fix the issue, feel free to submit a PR. Otherwise you might find support on stackoverflow. I'll close this issue for now as I can't recreate it.

**Closed by chmac** 2020-04-28 11:29 UTC
