### ISSUE TITLE
tag.js file error

### ISSUE THREAD

**Issue by khushbukotwal** [GatsbyCentral/gatsby-starter-wordpress#56] opened 2020-05-13 12:50 UTC
when I run gatsby develop it gives me this error

There was an error in your GraphQL query:

Field "tags" is not defined by type wordpress__POSTFilterInput. Did you mean status?

**Comment by eboyer** [comment] 2020-05-17 04:35
Having the same issue myself, just spinning this up for the first time and trying it out.

**Comment by chmac** [comment] 2020-05-17 14:48
Can you post a reproduction of this bug? Or did you find a fix?

I'm unable to reproduce it here. I clone this repo, then run `npm i && npm start` and the app loads, pages work, no errors. I'm assuming you've upgraded gatsby or some other package. Unfortunately Gatsby has changed their structure quite often and so these queries often break during upgrades. Would be great if Gatsby offered more stable updates, but that's outside of our control.

I'll close this issue now as I assume it's unrelated to our codebase. Potentially you've already connected to your own WordPress instance, and the issue lies there. If you can provide a reproduction we'll try to look into this further. Otherwise you may find success on stackoverflow, we don't provide support here, only bug reports.

**Closed by chmac** 2020-05-17 14:48 UTC

**Comment by eboyer** [comment] 2020-05-17 18:12
@chmac ~ Damn, quick close! No chance to discuss or dive in. Interesting approach.

@khushbukotwal ~ I had followed the directions in the readme on a fresh WP install but missed one key item related to tags: at least 1 tag must be assigned to 1 post. I had actually done that with categories and simply just created the tags. This fixed it for me!

**Comment by chmac** [comment] 2020-05-17 20:22
@eboyer Glad you fixed your issue. We have a bunch of Gatsby code in the wild, this is a retired side project, so there's no budget to provide user support free of charge. I've added a note to the readme asking folks to post on stackoverflow or similar and only post bugs with a reproduction here.

**Comment by eboyer** [comment] 2020-05-17 21:09
I’m unfamiliar with the rates for open source software support. What do you guys charge?

**Comment by khushbukotwal** [comment] 2020-05-18 05:16
@eboyer Thanks for the update. I'll follow.

**Comment by chmac** [comment] 2020-05-18 12:34
@eboyer Pricing is at superlumen.io
